### ISSUE TITLE
Check if dumps generated with wdsub can be uploaded to a query service

### ISSUE THREAD

**Issue by labra** [weso/weso-scholia#17]
wdsub is now able to generate dumps. 

For example, the latest run with a shex to obtain wikidata cities finished and returned 9151 entities in a dump which occupies 3Gb. 

I would like to check if it is possible to upload the contents of those dumps to a query service.

**Comment by thewillyhuman** [comment]
Until now the generated dumps follow the JSON representation. Tbomk the input processes are made for ttl files... And, after checking with some of the people from the Wikidata community they stated that the JSON format is aimed to process data but not to import it.
