### ISSUE TITLE
What is WESO?

### ISSUE THREAD

**Issue by dpriskorn** [weso/weso-scholia#22]
Could you add a little about it in the readme and maybe a link?

**Comment by thewillyhuman** [comment]
Hi @dpriskorn,

WESO (https://www.weso.es) refers to the Web Semantics Oviedo research group. We're a research group from the University of Oviedo (https://www.uniovi.es) (Spain). 

Thank you very much for your issue, you are completely and we will add the readme information ASAP.

**Comment by thewillyhuman** [comment]
Hi, @dpriskorn this issue has been fixed in #23.
